# Training Settings
base_path:
  value: "/local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/"
  help: "base directory of your data"

num_frames:
  value: 200
  help: "Duration of the input segments, eg: 200 for 2 second"

max_epoch:
  value: 200
  help: "Maximum number of epochs"

batch_size:
  value: 32
  help: "Batch size"

n_cpu:
  value: 8
  help: "Number of loader threads"

test_step:
  value: 1
  help: "Test and save every [test_step] epochs"

lr:
  value: 0.001
  help: "Learning rate"

lr_decay:
  value: 0.97
  help: "Learning rate decay every [test_step] epochs"


# Training and evaluation path/lists, save path

train_list:
  help: "All paths to training list"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/vietnam-celeb-t.txt.edited


train_path:
  help: "Directory to training data where speaker audio are stored"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data

    
eval_list:
  help: "All paths to evaluation list"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/vietnam-celeb-e.txt.edited


eval_path:
  help: "All paths to evaluation data"
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/vietnam_celeb/data


musan_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/musan_split
  help: 'The path to the MUSAN set, eg:"data/musan_split" in my case'

rir_path:
  value: /local_disk/helios/mmlamah/projects/kiwano-project/recipes/resnet/db/rirs_noises/RIRS_NOISES/simulated_rirs
  help: 'The path to the RIR set, eg:"data/RIRS_NOISES/simulated_rirs" in my case'

save_path:
  value: exps/exp_nas_vietnam_celeb_relu_26
  help: |
    Path to save the score.txt and models
    Pretrain without relu: exps/exp_nas_vietnam_celeb
    Pretrain with relu: exps/exp_nas_vietnam_celeb_relu
    exps/exp_nas_vietnam_celeb_relu_20 (model_0020.genotype - iteration 20)
    exps/exp_nas_vietnam_celeb_relu_26
    exps/exp_nas_vietnam_celeb_relu_42
    exps/exp_nas_vietnam_celeb_relu_47
    exps/exp_nas_vietnam_celeb_relu_76
    exps/exp_nas_vietnam_celeb_relu_15_2

initial_model:
  value: ""
  help: |
    Path of the initial_model
    exps/exp_resnet5/model/model_0080.model
    exps/exp_resnet5/model/best.model

# Model and Loss settings
C:
  value: 128
  help: "Init channel size"

m:
  value: 0.2
  help: "Loss margin in AAM softmax"

s:
  value: 30
  help: "Loss scale in AAM softmax"

n_class:
  help: "Number of speakers"
  value: 880

n_layers:
  value: 8
  help: "Number of layers for cell"
    
genotype_path:
  value: "exps/exp_nas_search_vietnam_celeb/model_0026.genotype"
  help: |
    The path for the genotype
    exps/exp_nas_search_vietnam_celeb/pretrain.genotype
    exps/exp_nas_search_vietnam_celeb/model_0020.genotype
    exps/exp_nas_search_vietnam_celeb/model_0026.genotype
    exps/exp_nas_search_vietnam_celeb/model_0042.genotype
    exps/exp_nas_search_vietnam_celeb/model_0047.genotype
    exps/exp_nas_search_vietnam_celeb/model_0076.genotype
    exps/exp_nas_search_2_vietnam_celeb/model_0015.genotype
    
    

drop_proba:
  value: 0.0
  help: "Proba dropping layer"

# Command
eval:
  value: false
  help: "Only do evaluation"

